def draw(count):
    if count == 1:
        print('===========')
        print('|         |')
        print('|         |')
        print('|         |')
        print('|         |')
        print('|         |')
    elif count == 2:
        print('===========')
        print('|    |    |')
        print('|         |')
        print('|         |')
        print('|         |')
        print('|         |')
    elif count == 3:
        print('===========')
        print('|    |    |')
        print('|    O    |')
        print('|         |')
        print('|         |')
        print('|         |')
    elif count == 4:
        print('===========')
        print('|    |    |')
        print('|    O    |')
        print('|    |    |')
        print('|         |')
        print('|         |')
    elif count == 5:
        print('===========')
        print('|    |    |')
        print('|    O    |')
        print('|   /|    |')
        print('|         |')
        print('|         |')
    elif count == 6:
        print('===========')
        print('|    |    |')
        print('|    O    |')
        print('|   /|\   |')
        print('|         |')
        print('|         |')
    elif count == 7:
        print('===========')
        print('|    |    |')
        print('|    O    |')
        print('|   /|\   |')
        print('|   /     |')
        print('|         |')
    else:
        print('===========')
        print('|    |    |')
        print('|    O    |')
        print('|   /|\   |')
        print('|   / \   |')
        print('|         |')
